# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cagu/WMR/intern_project/summer_work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cagu/WMR/intern_project/summer_work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cagu/WMR/intern_project/summer_work/CMakeFiles /home/cagu/WMR/intern_project/summer_work/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cagu/WMR/intern_project/summer_work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assignmentHandler

# Build rule for target.
assignmentHandler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assignmentHandler
.PHONY : assignmentHandler

# fast build rule for target.
assignmentHandler/fast:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/build
.PHONY : assignmentHandler/fast

#=============================================================================
# Target rules for targets named agvForwarder

# Build rule for target.
agvForwarder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agvForwarder
.PHONY : agvForwarder

# fast build rule for target.
agvForwarder/fast:
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/build
.PHONY : agvForwarder/fast

#=============================================================================
# Target rules for targets named workerHandler

# Build rule for target.
workerHandler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 workerHandler
.PHONY : workerHandler

# fast build rule for target.
workerHandler/fast:
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/build
.PHONY : workerHandler/fast

#=============================================================================
# Target rules for targets named taskPublisher

# Build rule for target.
taskPublisher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taskPublisher
.PHONY : taskPublisher

# fast build rule for target.
taskPublisher/fast:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/build
.PHONY : taskPublisher/fast

#=============================================================================
# Target rules for targets named taskHandler

# Build rule for target.
taskHandler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taskHandler
.PHONY : taskHandler

# fast build rule for target.
taskHandler/fast:
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/build
.PHONY : taskHandler/fast

#=============================================================================
# Target rules for targets named userInput

# Build rule for target.
userInput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 userInput
.PHONY : userInput

# fast build rule for target.
userInput/fast:
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/build
.PHONY : userInput/fast

#=============================================================================
# Target rules for targets named tableGenerator

# Build rule for target.
tableGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tableGenerator
.PHONY : tableGenerator

# fast build rule for target.
tableGenerator/fast:
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/build
.PHONY : tableGenerator/fast

#=============================================================================
# Target rules for targets named taskSubscriber

# Build rule for target.
taskSubscriber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taskSubscriber
.PHONY : taskSubscriber

# fast build rule for target.
taskSubscriber/fast:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/build
.PHONY : taskSubscriber/fast

#=============================================================================
# Target rules for targets named agv

# Build rule for target.
agv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agv
.PHONY : agv

# fast build rule for target.
agv/fast:
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/build
.PHONY : agv/fast

Robot.o: Robot.cpp.o

.PHONY : Robot.o

# target to build an object file
Robot.cpp.o:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/Robot.cpp.o
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/Robot.cpp.o
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/Robot.cpp.o
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/Robot.cpp.o
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/Robot.cpp.o
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/Robot.cpp.o
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/Robot.cpp.o
.PHONY : Robot.cpp.o

Robot.i: Robot.cpp.i

.PHONY : Robot.i

# target to preprocess a source file
Robot.cpp.i:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/Robot.cpp.i
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/Robot.cpp.i
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/Robot.cpp.i
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/Robot.cpp.i
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/Robot.cpp.i
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/Robot.cpp.i
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/Robot.cpp.i
.PHONY : Robot.cpp.i

Robot.s: Robot.cpp.s

.PHONY : Robot.s

# target to generate assembly for a file
Robot.cpp.s:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/Robot.cpp.s
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/Robot.cpp.s
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/Robot.cpp.s
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/Robot.cpp.s
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/Robot.cpp.s
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/Robot.cpp.s
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/Robot.cpp.s
.PHONY : Robot.cpp.s

SQLAPIcoms.o: SQLAPIcoms.cpp.o

.PHONY : SQLAPIcoms.o

# target to build an object file
SQLAPIcoms.cpp.o:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/SQLAPIcoms.cpp.o
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/SQLAPIcoms.cpp.o
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/SQLAPIcoms.cpp.o
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/SQLAPIcoms.cpp.o
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/SQLAPIcoms.cpp.o
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/SQLAPIcoms.cpp.o
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/SQLAPIcoms.cpp.o
.PHONY : SQLAPIcoms.cpp.o

SQLAPIcoms.i: SQLAPIcoms.cpp.i

.PHONY : SQLAPIcoms.i

# target to preprocess a source file
SQLAPIcoms.cpp.i:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/SQLAPIcoms.cpp.i
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/SQLAPIcoms.cpp.i
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/SQLAPIcoms.cpp.i
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/SQLAPIcoms.cpp.i
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/SQLAPIcoms.cpp.i
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/SQLAPIcoms.cpp.i
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/SQLAPIcoms.cpp.i
.PHONY : SQLAPIcoms.cpp.i

SQLAPIcoms.s: SQLAPIcoms.cpp.s

.PHONY : SQLAPIcoms.s

# target to generate assembly for a file
SQLAPIcoms.cpp.s:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/SQLAPIcoms.cpp.s
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/SQLAPIcoms.cpp.s
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/SQLAPIcoms.cpp.s
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/SQLAPIcoms.cpp.s
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/SQLAPIcoms.cpp.s
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/SQLAPIcoms.cpp.s
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/SQLAPIcoms.cpp.s
.PHONY : SQLAPIcoms.cpp.s

ZMQcoms.o: ZMQcoms.cpp.o

.PHONY : ZMQcoms.o

# target to build an object file
ZMQcoms.cpp.o:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/ZMQcoms.cpp.o
.PHONY : ZMQcoms.cpp.o

ZMQcoms.i: ZMQcoms.cpp.i

.PHONY : ZMQcoms.i

# target to preprocess a source file
ZMQcoms.cpp.i:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/ZMQcoms.cpp.i
.PHONY : ZMQcoms.cpp.i

ZMQcoms.s: ZMQcoms.cpp.s

.PHONY : ZMQcoms.s

# target to generate assembly for a file
ZMQcoms.cpp.s:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/ZMQcoms.cpp.s
.PHONY : ZMQcoms.cpp.s

agv.o: agv.cpp.o

.PHONY : agv.o

# target to build an object file
agv.cpp.o:
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/agv.cpp.o
.PHONY : agv.cpp.o

agv.i: agv.cpp.i

.PHONY : agv.i

# target to preprocess a source file
agv.cpp.i:
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/agv.cpp.i
.PHONY : agv.cpp.i

agv.s: agv.cpp.s

.PHONY : agv.s

# target to generate assembly for a file
agv.cpp.s:
	$(MAKE) -f CMakeFiles/agv.dir/build.make CMakeFiles/agv.dir/agv.cpp.s
.PHONY : agv.cpp.s

agvForwarder.o: agvForwarder.cpp.o

.PHONY : agvForwarder.o

# target to build an object file
agvForwarder.cpp.o:
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/agvForwarder.cpp.o
.PHONY : agvForwarder.cpp.o

agvForwarder.i: agvForwarder.cpp.i

.PHONY : agvForwarder.i

# target to preprocess a source file
agvForwarder.cpp.i:
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/agvForwarder.cpp.i
.PHONY : agvForwarder.cpp.i

agvForwarder.s: agvForwarder.cpp.s

.PHONY : agvForwarder.s

# target to generate assembly for a file
agvForwarder.cpp.s:
	$(MAKE) -f CMakeFiles/agvForwarder.dir/build.make CMakeFiles/agvForwarder.dir/agvForwarder.cpp.s
.PHONY : agvForwarder.cpp.s

assignmentHandler.o: assignmentHandler.cpp.o

.PHONY : assignmentHandler.o

# target to build an object file
assignmentHandler.cpp.o:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/assignmentHandler.cpp.o
.PHONY : assignmentHandler.cpp.o

assignmentHandler.i: assignmentHandler.cpp.i

.PHONY : assignmentHandler.i

# target to preprocess a source file
assignmentHandler.cpp.i:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/assignmentHandler.cpp.i
.PHONY : assignmentHandler.cpp.i

assignmentHandler.s: assignmentHandler.cpp.s

.PHONY : assignmentHandler.s

# target to generate assembly for a file
assignmentHandler.cpp.s:
	$(MAKE) -f CMakeFiles/assignmentHandler.dir/build.make CMakeFiles/assignmentHandler.dir/assignmentHandler.cpp.s
.PHONY : assignmentHandler.cpp.s

tableGenerator.o: tableGenerator.cpp.o

.PHONY : tableGenerator.o

# target to build an object file
tableGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/tableGenerator.cpp.o
.PHONY : tableGenerator.cpp.o

tableGenerator.i: tableGenerator.cpp.i

.PHONY : tableGenerator.i

# target to preprocess a source file
tableGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/tableGenerator.cpp.i
.PHONY : tableGenerator.cpp.i

tableGenerator.s: tableGenerator.cpp.s

.PHONY : tableGenerator.s

# target to generate assembly for a file
tableGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/tableGenerator.dir/build.make CMakeFiles/tableGenerator.dir/tableGenerator.cpp.s
.PHONY : tableGenerator.cpp.s

taskHandler.o: taskHandler.cpp.o

.PHONY : taskHandler.o

# target to build an object file
taskHandler.cpp.o:
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/taskHandler.cpp.o
.PHONY : taskHandler.cpp.o

taskHandler.i: taskHandler.cpp.i

.PHONY : taskHandler.i

# target to preprocess a source file
taskHandler.cpp.i:
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/taskHandler.cpp.i
.PHONY : taskHandler.cpp.i

taskHandler.s: taskHandler.cpp.s

.PHONY : taskHandler.s

# target to generate assembly for a file
taskHandler.cpp.s:
	$(MAKE) -f CMakeFiles/taskHandler.dir/build.make CMakeFiles/taskHandler.dir/taskHandler.cpp.s
.PHONY : taskHandler.cpp.s

taskPublisher.o: taskPublisher.cpp.o

.PHONY : taskPublisher.o

# target to build an object file
taskPublisher.cpp.o:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/taskPublisher.cpp.o
.PHONY : taskPublisher.cpp.o

taskPublisher.i: taskPublisher.cpp.i

.PHONY : taskPublisher.i

# target to preprocess a source file
taskPublisher.cpp.i:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/taskPublisher.cpp.i
.PHONY : taskPublisher.cpp.i

taskPublisher.s: taskPublisher.cpp.s

.PHONY : taskPublisher.s

# target to generate assembly for a file
taskPublisher.cpp.s:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/taskPublisher.cpp.s
.PHONY : taskPublisher.cpp.s

taskSubscriber.o: taskSubscriber.cpp.o

.PHONY : taskSubscriber.o

# target to build an object file
taskSubscriber.cpp.o:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/taskSubscriber.cpp.o
.PHONY : taskSubscriber.cpp.o

taskSubscriber.i: taskSubscriber.cpp.i

.PHONY : taskSubscriber.i

# target to preprocess a source file
taskSubscriber.cpp.i:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/taskSubscriber.cpp.i
.PHONY : taskSubscriber.cpp.i

taskSubscriber.s: taskSubscriber.cpp.s

.PHONY : taskSubscriber.s

# target to generate assembly for a file
taskSubscriber.cpp.s:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/taskSubscriber.cpp.s
.PHONY : taskSubscriber.cpp.s

userInput.o: userInput.cpp.o

.PHONY : userInput.o

# target to build an object file
userInput.cpp.o:
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/userInput.cpp.o
.PHONY : userInput.cpp.o

userInput.i: userInput.cpp.i

.PHONY : userInput.i

# target to preprocess a source file
userInput.cpp.i:
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/userInput.cpp.i
.PHONY : userInput.cpp.i

userInput.s: userInput.cpp.s

.PHONY : userInput.s

# target to generate assembly for a file
userInput.cpp.s:
	$(MAKE) -f CMakeFiles/userInput.dir/build.make CMakeFiles/userInput.dir/userInput.cpp.s
.PHONY : userInput.cpp.s

workerHandler.o: workerHandler.cpp.o

.PHONY : workerHandler.o

# target to build an object file
workerHandler.cpp.o:
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/workerHandler.cpp.o
.PHONY : workerHandler.cpp.o

workerHandler.i: workerHandler.cpp.i

.PHONY : workerHandler.i

# target to preprocess a source file
workerHandler.cpp.i:
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/workerHandler.cpp.i
.PHONY : workerHandler.cpp.i

workerHandler.s: workerHandler.cpp.s

.PHONY : workerHandler.s

# target to generate assembly for a file
workerHandler.cpp.s:
	$(MAKE) -f CMakeFiles/workerHandler.dir/build.make CMakeFiles/workerHandler.dir/workerHandler.cpp.s
.PHONY : workerHandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... assignmentHandler"
	@echo "... agvForwarder"
	@echo "... workerHandler"
	@echo "... taskPublisher"
	@echo "... edit_cache"
	@echo "... taskHandler"
	@echo "... userInput"
	@echo "... tableGenerator"
	@echo "... rebuild_cache"
	@echo "... taskSubscriber"
	@echo "... agv"
	@echo "... Robot.o"
	@echo "... Robot.i"
	@echo "... Robot.s"
	@echo "... SQLAPIcoms.o"
	@echo "... SQLAPIcoms.i"
	@echo "... SQLAPIcoms.s"
	@echo "... ZMQcoms.o"
	@echo "... ZMQcoms.i"
	@echo "... ZMQcoms.s"
	@echo "... agv.o"
	@echo "... agv.i"
	@echo "... agv.s"
	@echo "... agvForwarder.o"
	@echo "... agvForwarder.i"
	@echo "... agvForwarder.s"
	@echo "... assignmentHandler.o"
	@echo "... assignmentHandler.i"
	@echo "... assignmentHandler.s"
	@echo "... tableGenerator.o"
	@echo "... tableGenerator.i"
	@echo "... tableGenerator.s"
	@echo "... taskHandler.o"
	@echo "... taskHandler.i"
	@echo "... taskHandler.s"
	@echo "... taskPublisher.o"
	@echo "... taskPublisher.i"
	@echo "... taskPublisher.s"
	@echo "... taskSubscriber.o"
	@echo "... taskSubscriber.i"
	@echo "... taskSubscriber.s"
	@echo "... userInput.o"
	@echo "... userInput.i"
	@echo "... userInput.s"
	@echo "... workerHandler.o"
	@echo "... workerHandler.i"
	@echo "... workerHandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

