# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cagu/WMR/intern_project/summer_work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cagu/WMR/intern_project/summer_work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cagu/WMR/intern_project/summer_work/CMakeFiles /home/cagu/WMR/intern_project/summer_work/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cagu/WMR/intern_project/summer_work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taskSubscriber

# Build rule for target.
taskSubscriber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taskSubscriber
.PHONY : taskSubscriber

# fast build rule for target.
taskSubscriber/fast:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/build
.PHONY : taskSubscriber/fast

#=============================================================================
# Target rules for targets named taskPublisher

# Build rule for target.
taskPublisher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taskPublisher
.PHONY : taskPublisher

# fast build rule for target.
taskPublisher/fast:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/build
.PHONY : taskPublisher/fast

#=============================================================================
# Target rules for targets named test_sub

# Build rule for target.
test_sub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sub
.PHONY : test_sub

# fast build rule for target.
test_sub/fast:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/build
.PHONY : test_sub/fast

#=============================================================================
# Target rules for targets named test_pub

# Build rule for target.
test_pub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pub
.PHONY : test_pub

# fast build rule for target.
test_pub/fast:
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/build
.PHONY : test_pub/fast

#=============================================================================
# Target rules for targets named tableGenerator2

# Build rule for target.
tableGenerator2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tableGenerator2
.PHONY : tableGenerator2

# fast build rule for target.
tableGenerator2/fast:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/build
.PHONY : tableGenerator2/fast

Robot.o: Robot.cpp.o

.PHONY : Robot.o

# target to build an object file
Robot.cpp.o:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/Robot.cpp.o
.PHONY : Robot.cpp.o

Robot.i: Robot.cpp.i

.PHONY : Robot.i

# target to preprocess a source file
Robot.cpp.i:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/Robot.cpp.i
.PHONY : Robot.cpp.i

Robot.s: Robot.cpp.s

.PHONY : Robot.s

# target to generate assembly for a file
Robot.cpp.s:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/Robot.cpp.s
.PHONY : Robot.cpp.s

SQLAPIcoms.o: SQLAPIcoms.cpp.o

.PHONY : SQLAPIcoms.o

# target to build an object file
SQLAPIcoms.cpp.o:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/SQLAPIcoms.cpp.o
.PHONY : SQLAPIcoms.cpp.o

SQLAPIcoms.i: SQLAPIcoms.cpp.i

.PHONY : SQLAPIcoms.i

# target to preprocess a source file
SQLAPIcoms.cpp.i:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/SQLAPIcoms.cpp.i
.PHONY : SQLAPIcoms.cpp.i

SQLAPIcoms.s: SQLAPIcoms.cpp.s

.PHONY : SQLAPIcoms.s

# target to generate assembly for a file
SQLAPIcoms.cpp.s:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/SQLAPIcoms.cpp.s
.PHONY : SQLAPIcoms.cpp.s

ZMQcoms.o: ZMQcoms.cpp.o

.PHONY : ZMQcoms.o

# target to build an object file
ZMQcoms.cpp.o:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/ZMQcoms.cpp.o
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/ZMQcoms.cpp.o
.PHONY : ZMQcoms.cpp.o

ZMQcoms.i: ZMQcoms.cpp.i

.PHONY : ZMQcoms.i

# target to preprocess a source file
ZMQcoms.cpp.i:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/ZMQcoms.cpp.i
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/ZMQcoms.cpp.i
.PHONY : ZMQcoms.cpp.i

ZMQcoms.s: ZMQcoms.cpp.s

.PHONY : ZMQcoms.s

# target to generate assembly for a file
ZMQcoms.cpp.s:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/ZMQcoms.cpp.s
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/ZMQcoms.cpp.s
.PHONY : ZMQcoms.cpp.s

tableGenerator2.o: tableGenerator2.cpp.o

.PHONY : tableGenerator2.o

# target to build an object file
tableGenerator2.cpp.o:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/tableGenerator2.cpp.o
.PHONY : tableGenerator2.cpp.o

tableGenerator2.i: tableGenerator2.cpp.i

.PHONY : tableGenerator2.i

# target to preprocess a source file
tableGenerator2.cpp.i:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/tableGenerator2.cpp.i
.PHONY : tableGenerator2.cpp.i

tableGenerator2.s: tableGenerator2.cpp.s

.PHONY : tableGenerator2.s

# target to generate assembly for a file
tableGenerator2.cpp.s:
	$(MAKE) -f CMakeFiles/tableGenerator2.dir/build.make CMakeFiles/tableGenerator2.dir/tableGenerator2.cpp.s
.PHONY : tableGenerator2.cpp.s

taskPublisher.o: taskPublisher.cpp.o

.PHONY : taskPublisher.o

# target to build an object file
taskPublisher.cpp.o:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/taskPublisher.cpp.o
.PHONY : taskPublisher.cpp.o

taskPublisher.i: taskPublisher.cpp.i

.PHONY : taskPublisher.i

# target to preprocess a source file
taskPublisher.cpp.i:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/taskPublisher.cpp.i
.PHONY : taskPublisher.cpp.i

taskPublisher.s: taskPublisher.cpp.s

.PHONY : taskPublisher.s

# target to generate assembly for a file
taskPublisher.cpp.s:
	$(MAKE) -f CMakeFiles/taskPublisher.dir/build.make CMakeFiles/taskPublisher.dir/taskPublisher.cpp.s
.PHONY : taskPublisher.cpp.s

taskSubscriber.o: taskSubscriber.cpp.o

.PHONY : taskSubscriber.o

# target to build an object file
taskSubscriber.cpp.o:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/taskSubscriber.cpp.o
.PHONY : taskSubscriber.cpp.o

taskSubscriber.i: taskSubscriber.cpp.i

.PHONY : taskSubscriber.i

# target to preprocess a source file
taskSubscriber.cpp.i:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/taskSubscriber.cpp.i
.PHONY : taskSubscriber.cpp.i

taskSubscriber.s: taskSubscriber.cpp.s

.PHONY : taskSubscriber.s

# target to generate assembly for a file
taskSubscriber.cpp.s:
	$(MAKE) -f CMakeFiles/taskSubscriber.dir/build.make CMakeFiles/taskSubscriber.dir/taskSubscriber.cpp.s
.PHONY : taskSubscriber.cpp.s

test_pub.o: test_pub.cpp.o

.PHONY : test_pub.o

# target to build an object file
test_pub.cpp.o:
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/test_pub.cpp.o
.PHONY : test_pub.cpp.o

test_pub.i: test_pub.cpp.i

.PHONY : test_pub.i

# target to preprocess a source file
test_pub.cpp.i:
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/test_pub.cpp.i
.PHONY : test_pub.cpp.i

test_pub.s: test_pub.cpp.s

.PHONY : test_pub.s

# target to generate assembly for a file
test_pub.cpp.s:
	$(MAKE) -f CMakeFiles/test_pub.dir/build.make CMakeFiles/test_pub.dir/test_pub.cpp.s
.PHONY : test_pub.cpp.s

test_sub.o: test_sub.cpp.o

.PHONY : test_sub.o

# target to build an object file
test_sub.cpp.o:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/test_sub.cpp.o
.PHONY : test_sub.cpp.o

test_sub.i: test_sub.cpp.i

.PHONY : test_sub.i

# target to preprocess a source file
test_sub.cpp.i:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/test_sub.cpp.i
.PHONY : test_sub.cpp.i

test_sub.s: test_sub.cpp.s

.PHONY : test_sub.s

# target to generate assembly for a file
test_sub.cpp.s:
	$(MAKE) -f CMakeFiles/test_sub.dir/build.make CMakeFiles/test_sub.dir/test_sub.cpp.s
.PHONY : test_sub.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... taskSubscriber"
	@echo "... taskPublisher"
	@echo "... test_sub"
	@echo "... edit_cache"
	@echo "... test_pub"
	@echo "... tableGenerator2"
	@echo "... Robot.o"
	@echo "... Robot.i"
	@echo "... Robot.s"
	@echo "... SQLAPIcoms.o"
	@echo "... SQLAPIcoms.i"
	@echo "... SQLAPIcoms.s"
	@echo "... ZMQcoms.o"
	@echo "... ZMQcoms.i"
	@echo "... ZMQcoms.s"
	@echo "... tableGenerator2.o"
	@echo "... tableGenerator2.i"
	@echo "... tableGenerator2.s"
	@echo "... taskPublisher.o"
	@echo "... taskPublisher.i"
	@echo "... taskPublisher.s"
	@echo "... taskSubscriber.o"
	@echo "... taskSubscriber.i"
	@echo "... taskSubscriber.s"
	@echo "... test_pub.o"
	@echo "... test_pub.i"
	@echo "... test_pub.s"
	@echo "... test_sub.o"
	@echo "... test_sub.i"
	@echo "... test_sub.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

